---
#--------------------------------------------------------
# Hexo-Theme-MengD(萌典)
# 项目地址：https://github.com/lete114/hexo-theme-MengD
# 主题文档：https://mengd.js.org
# 一个简洁、轻量的Hexo主题
#--------------------------------------------------------

# 导航栏菜单
menu:
  enable: false
  首页: /
  友情链接: /link

# 图标
social:
  fab fa-github: https://github.com/lete114/hexo-theme-MengD
  fa fa-link: /link

favicon: /img/favicon.png
avatar: /img/logo.gif
pageCount: 5 # 首页展示文章数
darkmode: true # 深色模式
pjax: true # pjax
tags: false # 文章内是否显示标签

## 主题颜色
theme_color:
  main: '#e58a8a' # 主色
  fan: '#00c4b6' # 小风车
  body_a: '#00c4b6' # 全局a标签颜色
  title: '#ff7242' # 博主昵称

# 有趣的标题切换
amusing_title:
  enable: true
  leave_title: '(つェ⊂) 我藏好了哦~ '
  return_title: '(*´∇｀*) 被你发现啦~ '

# 自动截取
index_description:
  line: 3 # 显示多少行后出现省略号(...)
  length: 500 # 截取多少字

prefetch:
  enable: true # 是否启用预加载
  load: true # 是否在页面所有资源加载完毕后再进行预加载
  delay: 1000 # 延迟1秒后预加载
  threshold: 25 # 目标元素在浏览器可视区域25%时触发预加载
  # 自定义预加载资源，如果你开启了本地搜索功能，可以将下方的注释去掉，当使用搜索时不用等太长的请求时间
  customs: [/search.json]

# 图片懒加载
lazyload:
  enable: true
  loadimg: /img/load.gif

# 需安装插件: npm install hexo-generator-search --save
search:
  enable: true
  path: /search.xml
  field: post
  source: /js/search.js

# 代码块高亮主题
highlight_theme: mac # default / darker / pale night / light / ocean / mac / mac light
code_block_expand: # 是否开启代码块折叠
  enable: true
  height: 400 # 代码块高度超过400折叠 单位px
  scrollTop: 200 # 展开后,再次(手动点击)点击折叠滚动到代码块开始的距离 单位px

# https://github.com/lete114/hexo-minify
# 需要更全面的压缩请安装插件: npm install hexo-minify --save
minify:
  js: true
  css: true
  html: true

## 自定义侧边栏按钮
## 使用 || 分割
## setting: 点击设置按钮后显示   show: 直接显示
## 拥有3个属性：a标签属性|a标签描述|按钮图标
## #- harf="javascript:(0)"id="darkmode"||深色/浅色||fas fa-moon
rightside:
  settings:
    #- harf="javascript:(0)"id="darkmode"||深色/浅色||fas fa-moon ###渲染结果： <a harf="javascript:(0)" id="darkmode" title="深色/浅色"> <i class="fas fa-moon"></i> </a>
  show:
    #- harf="javascript:(0)"id="darkmode"||深色/浅色||fas fa-moon ###渲染结果： <a harf="javascript:(0)" id="darkmode" title="深色/浅色"> <i class="fas fa-moon"></i> </a>

# 侧边栏
# 详细: https://mengd.js.org/article/config.html#自定义侧边栏
sidebar:
  enable: true # 是否开启
  sticky: true # 固定显示
  area: left # 左边: left  右边: right

# 文章版权
copyright:
  enable: true
  author: MengD(萌典)
  mail: me@imlete.cn
  licenses: CC BY-NC-SA 4.0||https://creativecommons.org/licenses/by-nc-sa/4.0/ ## 文中||为分隔符，左侧为描述，右侧为版权许可
  description: 本博客所有文章除特别声明外，均采用||许可协议。转载请注明来自
  title: Hexo-Theme-MengD(萌典)

# 评论
## 注意大小写
comments: discuss # twikoo / waline / valine

discuss:
  source: https://lib.baomitu.com/discuss/1.1.4/dist/discuss.js
  serverURLs: https://env-jxscvzag.service.tcloudbase.com/discuss/mengd

# twikoo
## https://twikoo.js.org/
twikoo:
  envId: lete114-5g871u472d39809e #env-jxscvzag # 你的环境id
  region: ap-shanghai # 环境地域，ap-shanghai / ap-guangzhou
  path: window.location.pathname # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数

# 通过issues申请友情链接(目前只支持gitee)
link:
  issues:
    enable: false # 是否开启
    subtitle: Gitee友链 # 副标题
    owner: lete114 # 仓库拥有者
    repo: link # 仓库昵称
    show_position: later # 显示的位置  前(before) / 后(later)
  repo_pr:
    enable: true # 是否开启
    yml_url: https://cdn.jsdelivr.net/gh/lete114/links@latest/MengD/link.yml # 友链yml文件
    show_position: later # 显示的位置  前(before) / 后(later)

# 自定义引入外部css、js
import:
  headBefore: # 引入到<head>之后
    -
  headAfter: # 引入到</head>之前
    - <meta name="google-site-verification" content="uPApgr9zH7JO36gqOf48_UpfbFRRJ6zCf4cQd-s80eA" />
  bodyBefore: # 引入到<body>之后
    -
  bodyAfter: # 引入到</body>之前
    -
  # 例如：
  # - <link rel="stylesheet" href="/css/index.css">
  # - '<style>body{color: red}</style>' ## 注意由于css的‘{}’是关键符号所以需要(单/双)引号''
  # - <script>alert(1)</script>

# 页脚
footer:
  since: 2020
  custom_text: 我相信我可以，但我一直在路上，所以我有无限的可能！！
  icp:
    enable: false
    text:
    icon: /img/icp.png
    url: https://beian.miit.gov.cn/

# 统计(分析)
analytics:
  baidu: 8e216044fbe6b71b6fefc197c2508ed1
  google:

font:
  # 全局字体
  html: consolas,Menlo,'PingFang SC','Microsoft YaHei',sans-serif
  # 代码块字体
  code: consolas,Menlo,'PingFang SC','Microsoft YaHei',sans-serif

# 主题的css与js引入
## 无特殊要求请勿更改
CDN:
  main_js: /js/main.js
  main_css: /css/main.css
  utlis: /js/utlis.js
  # lazyload
  lazyload: /js/lazyload.js
  # pjax
  pjax: /third-party/js/pjax.js
  # prefetch
  prefetch: /third-party/js/prefetch-page.js
  # fancybox
  fancyboxJs: /third-party/js/fancybox.js
  fancyboxCss: /third-party/css/fancybox.css
  # fortawesome
  fortawesome: /third-party/fontawesome-free/css/all.min.css
