---
#--------------------------------------------------------
# Hexo-MengD(萌典)
# 项目地址：https://github.com/lete114/hexo-theme-MengD
# 主题文档：https://mengd.js.org
# 一个简洁、轻量的Hexo主题
#--------------------------------------------------------

# 导航栏菜单
menu:
  # 首页: /
  # 找文章:
  #   - 标签 || /tags
  #   - 分类 || /categories
  #   - 归档 || /archives
  # 友情链接: /link
  # 关于我: /about

# 图标
social:
  # fab fa-github: https://github.com/lete114
  # fa fa-envelope: mailto:lete@lete114.top

main_size: 50 # 文章显示大小(单位：百分比)
favicon: /img/favicon.png
avatar: /img/logo.gif
page_count: 5 # 首页展示文章数
MathJax: false # 数学公式
darkmode: true # 深色模式
pjax: true # pjax
tags: false # 文章内是否显示标签

## 主题颜色
theme_color:
  main: '#e58a8a' # 主色
  fan: '#00c4b6' # 小风车
  body_a: '#00c4b6' # 全局a标签颜色
  title: '#ff7242' # 博主昵称

# 有趣的标题切换
amusing_title:
  enable: true
  leave_title: '(つェ⊂) 我藏好了哦~ '
  return_title: '(*´∇｀*) 被你发现啦~ '

# 自动截取
description:
  line: 3 # 显示多少行后出现省略号(...)
  length: 500 # 截取多少字

# 图片懒加载
lazyload:
  enable: true
  loadimg: /img/load.gif

# 需安装插件: npm install hexo-generator-search --save
search:
  enable: true
  path: /search.xml
  field: post
  source: /js/search.js

# 代码块高亮主题
highlight_theme: mac # default / darker / pale night / light / ocean / mac / mac light
code_block_expand: # 是否开启代码块折叠
  enable: true
  height: 400 # 代码块高度超过400折叠 单位px
  scrollTop: 200 # 展开后,再次(手动点击)点击折叠滚动到代码块开始的距离 单位px

# https://github.com/lete114/hexo-minify
# 需要更全面的压缩请安装插件: npm install hexo-minify --save
minify:
  js: false
  css: true
  html: false

## 自定义侧边栏按钮
## 使用 || 分割
## setting: 点击设置按钮后显示   show: 直接显示
## 拥有3个属性：a标签属性|a标签描述|按钮图标
## #- harf="javascript:(0)"id="darkmode"||深色/浅色||fas fa-moon
rightside:
  settings:
    #- harf="javascript:(0)"id="darkmode"||深色/浅色||fas fa-moon ###渲染结果： <a harf="javascript:(0)" id="darkmode" title="深色/浅色"> <i class="fas fa-moon"></i> </a>
  show:
    #- harf="javascript:(0)"id="darkmode"||深色/浅色||fas fa-moon ###渲染结果： <a harf="javascript:(0)" id="darkmode" title="深色/浅色"> <i class="fas fa-moon"></i> </a>

# 文章版权
copyright:
  enable: true
  author: Lete乐特
  mail: lete@lete114.top
  licenses: CC BY-NC-SA 4.0||https://creativecommons.org/licenses/by-nc-sa/4.0/ ## 文中||为分隔符，左侧为描述，右侧为版权许可
  description: 本博客所有文章除特别声明外，均采用||许可协议。转载请注明来自
  title: Lete乐特's Blog

# 评论
## 注意大小写
comments: waline # twikoo / waline / valine

# valine
## https://valine.js.org/
valine:
  source: https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js
  appid: qvkfxxxxxxxxxxxxxxxxxxxxxbMMI # 你的 leancloud app id
  appkey: WOURxxxxxxxxxxxxxxxxxWJrog # 你的 leancloud app key
  placeholder: 快来评论吧!! #评论框占位符
  avatar: '' # gravatar style https://valine.js.org/#/avatar
  meta: ['nick', 'mail', 'link'] # 评论者相关属性
  pageSize: 5 # comment list page size
  lang: zh-CN # i18n: zh-CN/zh-TW/en/ja
  emojiCDN: # emoji CDN
  emojiMaps: # 自定义表情包
  enableQQ: true # enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  option: # 自定义添加 https://valine.js.org/configuration.html

# waline
## https://waline.js.org
waline:
  source: //cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
  serverURL: https://waline.vercel.app/ # 服务端地址
  placeholder: 快来评论吧!! #评论框占位符
  avatar: '' # gravatar style https://valine.js.org/#/avatar
  meta: ['nick', 'mail', 'link'] # 评论者相关属性
  pageSize: 5 # comment list page size
  lang: zh-CN # i18n: zh-CN/zh-TW/en/ja
  requiredFields: ['nick', 'mail', 'link'] # 评论人必填项
  emojiCDN: # emoji CDN
  emojiMaps: # 自定义表情包
  option: # 自定义添加 https://waline.js.org/client/basic.html

# twikoo
## https://twikoo.js.org/
twikoo:
  source: https://cdn.jsdelivr.net/npm/twikoo/dist/twikoo.all.min.js
  envId: xxxxxxxx # 你的环境id
  region: ap-shanghai # 环境地域，ap-shanghai / ap-guangzhou
  path: window.location.pathname # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
  option:

## 说说

# Artitalk
## https://artitalk.js.org/settings.html
artitalk:
  enable: false # 是否开启
  source: https://cdn.jsdelivr.net/npm/artitalk
  title: Artitalk # 标题
  path: artitalk/index.html # 路径
  appid: WhOxxxxxxxxxxxxxMMI #  LeanCloud appId
  appkey: M9Pxxxxxxxxxxxxxxx3Kvs # LeanCloud appKey
  serverURL: # 如果你是国内版 LeanCloud 用户，此项必填
  lang: # 语言设置 默认中文 zh / en / es
  atEmoji: # 自定义表情包
  option:

# HPP_talk
## https://hexoplusplus.js.org/
hpp_talk:
  enable: false # 是否开启
  source_css: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@9bf1085/talk.css
  source_js: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@9bf1085/talk_user.js
  title: HPP_talk # 标题
  path: hpp_talk/index.html # 路径
  domain: blog.lete114.workers.dev # 您的HexoPlusPlus域名
  limit: 10 # 单次获取的最多条数
  start: 0 # 从第几条开始
  option:

## 404页面
error_404:
  enable: true
  background: '#00c4b6'

# 通过issues申请友情链接(目前只支持gitee)
link:
  issues:
    enable: false # 是否开启
    subtitle: Gitee友链 # 副标题
    owner: lete114 # 仓库拥有者
    repo: link # 仓库昵称
    show_position: later # 显示的位置  前(before) / 后(later)
  repo_pr:
    enable: true # 是否开启
    yml_url: https://links.lete114.top/MengD/link.yml # 友链yml文件
    show_position: later # 显示的位置  前(before) / 后(later)

# 自定义引入外部css、js
import:
  head: # 引入到</head>之前
    -
  top: # 引入到<body>之后
    -
  bottom: # 引入到</body>之前
    -
  # 例如：
  # - <link rel="stylesheet" href="/css/index.css">
  # - '<style>body{color: red}</style>' ## 注意由于css的‘{}’是关键符号所以需要(单/双)引号''
  # - <script>alert(1)</script>

# 页脚
footer:
  since: 2020
  custom_text: 我相信我可以，但我一直在路上，所以我有无限的可能！！
  icp:
    enable: false
    text:
    icon: /img/icp.png
    url: https://beian.miit.gov.cn/

# 统计(分析)
analytics:
  baidu:
  google:

# 设置字体
font:
  # 全局字体
  html: 'Helvetica, Tahoma, Arial, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif'
  # 代码块字体
  code: 'Helvetica, Tahoma, Arial, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif'

# 主题的css与js引入
## 无特殊要求请勿更改
CDN:
  main_js: /js/main.js
  main_css: /css/main.css
  utlis: /js/utlis.js
  # lazyload
  lazyload: /js/lazyload.js
  # pjax
  pjax: https://cdn.jsdelivr.net/npm/pjax/pjax.min.js
  # fortawesome
  fortawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
  # yml转json
  js_yaml: https://cdn.jsdelivr.net/npm/js-yaml@latest/dist/js-yaml.min.js
  # math
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
