name: AutoDeployDocs

on: 
  push:
    branches: docs
  release:
    types: published
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    name: AutoDeployDocs
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@main

    - name: 安装 Node
      uses: actions/setup-node@main
      with:
        node-version: "12.x"
        
    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g
    - name: 缓存 Hexo
      uses: actions/cache@main
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: 安装依赖
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        npm install --save
    - name: 生成静态文件
      run: |
        hexo clean
        git clone -b gh-pages https://github.com/lete114/hexo-theme-MengD.git public
        hexo generate
    
    - name: 提交
      run: |
        cd ./public
        git config --global user.name "lete114"
        git config --global user.email "lete@lete114.top"
        git add .
        git commit -m "${{ github.event.head_commit.message }} - Auto Push Docs"
        #git push --force https://lete114:${{secrets.TOKEN}}@github.com/lete114/hexo-theme-MengD.git
    - name: 部署
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.TOKEN}}
